name: Telega Trigger

on:
  issue_comment:
    types: [created]

jobs:
  launchBackportBuild:
    runs-on: ubuntu-latest
    if: github.event.issue.pull_request != '' && contains(github.event.comment.body, '/telega')

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Assemble
      run: ./gradlew assembleDebug -Dec_accessToken="${{ secrets.EC_TOKEN }}"

    - name: Send apk to telegram
      uses: appleboy/telegram-action@master
      with:
        to: ${{ secrets.TELEGRAM_TO }}
        token: ${{ secrets.TELEGRAM_TOKEN }}
        message: |
          [trigger] ${{ github.event.pull_request.title }}
          ${{ github.base_ref }} <= ${{ github.head_ref }}
          PR: https://github.com/Wheellog/Wheellog.Android/pull/${{github.event.number}}
        document: app/build/outputs/apk/debug/app-debug.apk
