name: Telega Trigger

on:
  issue_comment:
    types: [created]

jobs:
  triggerTelega:
    runs-on: ubuntu-latest
    if: github.event.issue.pull_request != '' && github.event.comment.body == '/telega'

    steps:
    - name: GitHub API Request
      id: request
      uses: octokit/request-action@v2.0.0
      with:
        route: ${{ github.event.issue.pull_request.url }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Get PR informations
      id: pr_data
      run: |
        echo "::set-output name=branch::${{ fromJson(steps.request.outputs.data).head.ref }}"
        echo "::set-output name=repo_name::${{ fromJson(steps.request.outputs.data).base.repo.full_name }}"
        echo "::set-output name=repo_clone_url::${{ fromJson(steps.request.outputs.data).base.repo.clone_url }}"
        echo "::set-output name=repo_ssh_url::${{ fromJson(steps.request.outputs.data).base.repo.ssh_url }}"
        echo "::set-output name=userlogin::${{ fromJson(steps.request.outputs.data).head.user.login }}"
        echo "::set-output name=link::${{ fromJson(steps.request.outputs.data)._links.html.href }}"        
        echo "::set-output name=title::${{ fromJson(steps.request.outputs.data).title }}"        
        echo "::set-output name=number::${{ fromJson(steps.request.outputs.data).number }}"

    - name: Clone branch of PR
      uses: actions/checkout@v2
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        
    - name: Checkout PR
      uses: dawidd6/action-checkout-pr@v1.2.0
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        pr: ${{ steps.pr_data.outputs.number }}
        repo: ${{ steps.pr_data.outputs.repo_name }}
    
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Assemble
      run: ./gradlew assembleDebug -Dec_accessToken="${{ secrets.EC_TOKEN }}"

    - name: Send apk to telegram
      uses: appleboy/telegram-action@master
      with:
        to: ${{ secrets.TELEGRAM_TO }}
        token: ${{ secrets.TELEGRAM_TOKEN }}
        message: |
          [trigger] ${{ steps.pr_data.outputs.title }} 
          Branch ${{ steps.pr_data.outputs.branch }} from ${{ steps.pr_data.outputs.userlogin }}
          PR: ${{ steps.pr_data.outputs.link }}
        document: app/build/outputs/apk/debug/app-debug.apk
